stages:
  - name: snapshot
    if: branch = dev
  - name: release
    if: branch = master

jobs:
  include:
    - stage: snapshot
      script: ./gradlew bintrayUpload -PsnapshotNumber=$TRAVIS_BUILD_NUMBER
      os: linux
      language: java
      jdk: openjdk12
    - stage: release
      script: ./gradlew bintrayUpload
      os: linux
      language: java
      jdk: openjdk12
