name: Snapshot

on:
  push:
    branches:
      - master
      - 'snapshot/[0-9]+.[0-9]+'
      - 'kotlin/*'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./gradlew build
        shell: bash
      - name: Deploy
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
          BINTRAY_USER_ORG: ${{ secrets.BINTRAY_USER_ORG }}
        run: |
          eapVersion=${github_ref#*kotlin/*}
          [[ -z "$eapVersion" ]] && snapshotVersion="$GITHUB_RUN_NUMBER" || snapshotVersion="$eapVersion-$GITHUB_RUN_NUMBER"
          ./gradlew publish -PsnapshotNumber=$snapshotVersion
        shell: bash